name: Apli internet
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: On déploie à gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 16

      - name: Ouvrir la branche
        uses: actions/checkout@v2

      - name: Nétoyer les dépendances d'installation
        run: yarn install --frozen-lockfile

      - name: Déployer
        run: |
          git config user.name "julienmalard" && git config user.email "julien.malard@mail.mcgill.ca"
          branch=$(git branch --show-current)
          git checkout --orphan gh-pages
          yarn build
          cp dist/index.html dist/404.html
          touch dist/CNAME
          git --work-tree dist add --all
          git --work-tree dist commit -m "gh-pages"
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f $branch
          git branch -D gh-pages
